# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: kr
pipeline:
  - name: custom.tokenizer.MecabTokenizer
    mecab_dir: 'C:/mecab/mecab-ko-dic'
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: custom.featurizer.FlairFeaturizer
    epochs: 100
    model_size: 100
    seq_len: 100
  - name: custom.featurizer.WordEmbedFeaturizer
    # model: 'word2vec'
    # model_path: 'models/word2vec'
    model: 'fasttext'
    model_path: 'models/fasttext'
    model_size: 70
    window_size: 7
    min_count: 1
    epochs: 10
  - name: custom.classifier.CustomClassifier
    epochs: 1
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FormPolicy
